### ISSUE TITLE
URL No Longer Exists

### ISSUE THREAD

**Issue by v15h9** [atorman/elfPy#1]
When we use https://login.salesforce.com/services/oauth2/token&grant_type=password, we get a URL No Longer Exists error.

**Comment by atorman** [comment]
Hi Vishalashah - thanks for surfacing this!

Lines 73 - 74 refer to the oauth end point in this issue:

 # create a new salesforce REST API OAuth request
    url = 'https://login.salesforce.com/services/oauth2/token'
    data = '&grant_type=password&client_id='+CLIENT_ID+'&client_secret='+CLIENT_SECRET+'&username='+username+'&password='+password
    headers = {'X-PrettyPrint' : '1'}

However, the rest of the endpoint is missing: 

&client_id='+CLIENT_ID+'&client_secret='+CLIENT_SECRET+'&username='+username+'&password='+password
    headers = {'X-PrettyPrint' : '1'}

Can you please double check to make sure that the client id and secret are being passed?

Thanks!

**Comment by v15h9** [comment]
Yeah. To debug I stripped out the rest and hit this issue. Mainly the URL open gets an error. 

Do we need to encode the parameters?

__

Vishal

**Comment by atorman** [comment]
You shouldn't need to encode the parameters AFAIK, but you definitely need the full endpoint - if you strip off Client Id and Client Secret, it won't work. Check out Session Id Authorization section of the Rest API docs: https://www.salesforce.com/us/developer/docs/api_rest/Content/quickstart_oauth.htm

**Comment by v15h9** [comment]
Not sure why it didn't work first, seems to be working now.
